version: '3.8'

services:
  web:
    build: .
    container_name: card_inventory_app
    restart: unless-stopped
    volumes:
      - ./instance:/app/instance
    env_file: .env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    ports:
      - "5000:5000"

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: card_inventory_tunnel
    restart: unless-stopped
    command: tunnel run
    env_file: .env
    depends_on:
      - web
